apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtp-platform-qa
  namespace: srtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtp-platform-qa
  template:
    metadata:
      labels:
        app: rtp-platform-qa
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: srtp-itn-workload-identity
      containers:
        - name: gpd-producer
          image: ghcr.io/pagopa/rtp-platform-qa:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 300
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 300
          env:
            - name: KEYVAULT_NAME
              value: cstar-u-itn-srtp-kv
            - name: EVENTHUB_SECRET_NAME
              value: gpd-eventhub-connection-string
            - name: EVENTHUB_NAMESPACE
              value: pagopa-u-itn-gps-rtp-integration-evh
            - name: EVENTHUB_TOPIC
              value: rtp-events
---
apiVersion: v1
kind: Service
metadata:
  name: rtp-platform-qa-service
  namespace: srtp
spec:
  selector:
    app: rtp-platform-qa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rtp-platform-qa-ingress
  namespace: srtp
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: qa.internal.uat.cstar.pagopa.it
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rtp-platform-qa-service
                port:
                  number: 80
