name: Deploy on AKS

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        default: dev
        description: env

env:
  NAMESPACE: afm
  APP_NAME: rtp-platform-qa

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: [ self-hosted, self-hosted-job, "${{ github.event.inputs.environment || 'dev' }}" ]
    environment: ${{ github.event.inputs.environment || 'dev' }}
    steps:
      - uses: actions/checkout@v4

      - name: Check runner environment
        run: |
          echo "ğŸƒ Running on environment: ${{ github.event.inputs.environment || 'dev' }}"
          echo "ğŸ“¦ Namespace: ${{ env.NAMESPACE }}"
          echo "ğŸ“¦ App: ${{ env.APP_NAME }}"
