name: Manual Debt Position Tests

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Target environment'
        required: true
        default: 'uat'
        options:
          - uat
          - dev
      operation:
        type: choice
        description: 'Operation to be tested'
        required: true
        default: 'create'
        options:
          - create
          - delete
          - update
          - all

jobs:
  run_debt_position_tests:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    name: Test Debt Position - ${{ github.event.inputs.operation }} in ${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.11'

      - name: Install dependencies (functional tests)
        run: |
          make install-functional

      - name: Create debt position
        if: ${{ github.event.inputs.operation == 'create' || github.event.inputs.operation == 'all' }}
        env:
          DEBTOR_SERVICE_PROVIDER_CLIENT_ID: ${{ vars.DEBTOR_SERVICE_PROVIDER_CLIENT_ID }}
          DEBTOR_SERVICE_PROVIDER_ID: ${{ vars.DEBTOR_SERVICE_PROVIDER_ID }}
          DEBTOR_SERVICE_PROVIDER_CLIENT_SECRET: ${{ secrets.DEBTOR_SERVICE_PROVIDER_CLIENT_SECRET }}
          DEBT_POSITIONS_SUBSCRIPTION_KEY: ${{ github.event.inputs.environment == 'dev' && secrets.DEBT_POSITIONS_DEV_SUBSCRIPTION_KEY || secrets.DEBT_POSITIONS_SUBSCRIPTION_KEY }}
          DEBT_POSITIONS_DEV_SUBSCRIPTION_KEY: ${{ github.event.inputs.environment == 'dev' && secrets.DEBT_POSITIONS_DEV_SUBSCRIPTION_KEY || '' }}
          DEBT_POSITIONS_ORGANIZATION_ID: ${{ github.event.inputs.environment == 'dev' && vars.DEBT_POSITIONS_DEV_ORGANIZATION_ID || vars.DEBT_POSITIONS_ORGANIZATION_ID }}
          DEBT_POSITIONS_DEV_ORGANIZATION_ID: ${{ github.event.inputs.environment == 'dev' && vars.DEBT_POSITIONS_DEV_ORGANIZATION_ID || '' }}
        run: |
          pytest "functional-tests/tests/test_GPD_availability.py::test_create_debt_position[environment_${{ github.event.inputs.environment }}]" -v

      - name: Delete debt position
        if: ${{ github.event.inputs.operation == 'delete' || github.event.inputs.operation == 'all' }}
        env:
          DEBTOR_SERVICE_PROVIDER_CLIENT_ID: ${{ vars.DEBTOR_SERVICE_PROVIDER_CLIENT_ID }}
          DEBTOR_SERVICE_PROVIDER_ID: ${{ vars.DEBTOR_SERVICE_PROVIDER_ID }}
          DEBTOR_SERVICE_PROVIDER_CLIENT_SECRET: ${{ secrets.DEBTOR_SERVICE_PROVIDER_CLIENT_SECRET }}
          DEBT_POSITIONS_SUBSCRIPTION_KEY: ${{ github.event.inputs.environment == 'dev' && secrets.DEBT_POSITIONS_DEV_SUBSCRIPTION_KEY || secrets.DEBT_POSITIONS_SUBSCRIPTION_KEY }}
          DEBT_POSITIONS_DEV_SUBSCRIPTION_KEY: ${{ github.event.inputs.environment == 'dev' && secrets.DEBT_POSITIONS_DEV_SUBSCRIPTION_KEY || '' }}
          DEBT_POSITIONS_ORGANIZATION_ID: ${{ github.event.inputs.environment == 'dev' && vars.DEBT_POSITIONS_DEV_ORGANIZATION_ID || vars.DEBT_POSITIONS_ORGANIZATION_ID }}
          DEBT_POSITIONS_DEV_ORGANIZATION_ID: ${{ github.event.inputs.environment == 'dev' && vars.DEBT_POSITIONS_DEV_ORGANIZATION_ID || '' }}
        run: |
          pytest "functional-tests/tests/test_GPD_availability.py::test_delete_debt_position[environment_${{ github.event.inputs.environment }}]" -v

      - name: Update debt position
        if: ${{ github.event.inputs.operation == 'update' || github.event.inputs.operation == 'all' }}
        env:
          DEBTOR_SERVICE_PROVIDER_CLIENT_ID: ${{ vars.DEBTOR_SERVICE_PROVIDER_CLIENT_ID }}
          DEBTOR_SERVICE_PROVIDER_ID: ${{ vars.DEBTOR_SERVICE_PROVIDER_ID }}
          DEBTOR_SERVICE_PROVIDER_CLIENT_SECRET: ${{ secrets.DEBTOR_SERVICE_PROVIDER_CLIENT_SECRET }}
          DEBT_POSITIONS_SUBSCRIPTION_KEY: ${{ github.event.inputs.environment == 'dev' && secrets.DEBT_POSITIONS_DEV_SUBSCRIPTION_KEY || secrets.DEBT_POSITIONS_SUBSCRIPTION_KEY }}
          DEBT_POSITIONS_DEV_SUBSCRIPTION_KEY: ${{ github.event.inputs.environment == 'dev' && secrets.DEBT_POSITIONS_DEV_SUBSCRIPTION_KEY || '' }}
          DEBT_POSITIONS_ORGANIZATION_ID: ${{ github.event.inputs.environment == 'dev' && vars.DEBT_POSITIONS_DEV_ORGANIZATION_ID || vars.DEBT_POSITIONS_ORGANIZATION_ID }}
          DEBT_POSITIONS_DEV_ORGANIZATION_ID: ${{ github.event.inputs.environment == 'dev' && vars.DEBT_POSITIONS_DEV_ORGANIZATION_ID || '' }}
        run: |
          pytest "functional-tests/tests/test_GPD_availability.py::test_update_debt_position[environment_${{ github.event.inputs.environment }}]" -v
